# -*- coding: utf-8 -*-
"""Superstore

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14w-On5cylH-2i_Rsgv1UZ_9-MYNfoZ8G
"""

import pandas as pd
url = 'https://gist.githubusercontent.com/QuinQuin2012/178c70c4d6ae07d2aa8ea64f2bedc140/raw/9f01f8e74ded3d49ff6f5e95ba0f1f4b282f62d6/Superstore%2520(updated).csv'
superstore_df = pd.read_csv(url)
superstore_df.head()

superstore_df['Year']=pd.DatetimeIndex(superstore_df['Order Date']).year
superstore_df['Quarter']=pd.DatetimeIndex(superstore_df['Order Date']).quarter
superstore_df['Month']=pd.DatetimeIndex(superstore_df['Order Date']).month
superstore_df.head(5)

"""**Sort customer names in alphabetical order**"""

superstore_df.sort_values('Customer Name') [0:10]

"""**How many customers do we have?**"""

superstore_df['Customer Name'].value_counts()

"""**What were the revenue?**"""

superstore_df['Sales'].sum()

"""**What were our sales for the corporate segment? (What were our corporate sales?)**"""

superstore_df[superstore_df.Segment=='Corporate']['Sales'].sum()

"""**What were our sales by month in 2018?** **(2 cách)**"""

superstore_df[superstore_df.Year == 2018].groupby('Month')['Sales'].sum()

superstore_df[pd.to_datetime(superstore_df['Order Date']).dt.year == 2018]['Sales'].groupby(pd.to_datetime(superstore_df['Order Date']).dt.month).sum()

"""**What were sales in each state?**"""

sumofsales1 = superstore_df.groupby('State')['Sales'].sum()
sumofsales1.sort_values(ascending = False) [0:5]

"""**What were the top 5 cities based on sales?**"""

sumofsales2 = superstore_df.groupby('City')['Sales'].sum()
sumofsales2.sort_values(ascending = False)[0:5]

"""**How much profit did we make? By quarter?**"""

sumofprofit = superstore_df.groupby(['Year','Quarter'])['Profit'].sum()
sumofprofit.sort_values()

"""**What was the average profit per year?**"""

superstore_df.groupby('Year')['Profit'].mean()

"""**Which orders had high profits?**"""

superstore_df.groupby('Order ID')['Profit'].sum().sort_values(ascending = False).head(1)

"""**In California, what were the top 10 cities based on sales in 2018?**"""



"""**Compare revenue and profit ratio for each category and subcategory.**"""

result = superstore_df[['Sales', 'Profit']].groupby([superstore_df.Category, superstore_df['Sub-Category']]).sum()
result['Profit_Ratio'] = result.apply(lambda row: row.Profit / row.Sales, axis = 1)
print(result)